/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_MenuAjout (void)
{
  GtkWidget *MenuAjout;
  GtkWidget *fixed1;
  GtkObject *spinbuttonJourDepart_adj;
  GtkWidget *spinbuttonJourDepart;
  GtkObject *spinbuttonMois_adj;
  GtkWidget *spinbuttonMois;
  GtkObject *spinbuttonAnnee_adj;
  GtkWidget *spinbuttonAnnee;
  GtkObject *spinbuttonPrix_adj;
  GtkWidget *spinbuttonPrix;
  GtkWidget *comboboxClass;
  GtkWidget *label_6;
  GtkWidget *comboboxDestination;
  GtkWidget *label_7;
  GtkWidget *labelMsg;
  GtkWidget *buttonAppliquer;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label_15;
  GtkWidget *buttonRetour;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label_16;
  GtkWidget *label_3;
  GtkWidget *label_4;
  GtkWidget *label_14;
  GtkWidget *label_13;
  GtkWidget *label_8;
  GtkWidget *comboboxDepart;
  GtkWidget *label_5;
  GtkWidget *label_2;

  MenuAjout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (MenuAjout, 700, 500);
  gtk_window_set_title (GTK_WINDOW (MenuAjout), _("MenuAjout"));
  gtk_window_set_position (GTK_WINDOW (MenuAjout), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (MenuAjout), TRUE);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (MenuAjout), fixed1);

  spinbuttonJourDepart_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonJourDepart = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonJourDepart_adj), 1, 0);
  gtk_widget_show (spinbuttonJourDepart);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbuttonJourDepart, 224, 288);
  gtk_widget_set_size_request (spinbuttonJourDepart, 56, 29);

  spinbuttonMois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonMois = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonMois_adj), 1, 0);
  gtk_widget_show (spinbuttonMois);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbuttonMois, 336, 288);
  gtk_widget_set_size_request (spinbuttonMois, 56, 29);

  spinbuttonAnnee_adj = gtk_adjustment_new (2020, 2020, 2025, 1, 10, 10);
  spinbuttonAnnee = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonAnnee_adj), 1, 0);
  gtk_widget_show (spinbuttonAnnee);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbuttonAnnee, 448, 288);
  gtk_widget_set_size_request (spinbuttonAnnee, 64, 29);

  spinbuttonPrix_adj = gtk_adjustment_new (100, 100, 3000, 1, 10, 10);
  spinbuttonPrix = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonPrix_adj), 1, 0);
  gtk_widget_show (spinbuttonPrix);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbuttonPrix, 520, 152);
  gtk_widget_set_size_request (spinbuttonPrix, 56, 29);

  comboboxClass = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxClass);
  gtk_fixed_put (GTK_FIXED (fixed1), comboboxClass, 488, 64);
  gtk_widget_set_size_request (comboboxClass, 176, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxClass), _("ClasseEconomique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxClass), _("ClassePremium"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxClass), _("CasseAffaire"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxClass), _("ClassePremi\303\250re"));

  label_6 = gtk_label_new (_("Jours"));
  gtk_widget_show (label_6);
  gtk_fixed_put (GTK_FIXED (fixed1), label_6, 224, 256);
  gtk_widget_set_size_request (label_6, 54, 32);
  gtk_misc_set_padding (GTK_MISC (label_6), 5, 0);

  comboboxDestination = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxDestination);
  gtk_fixed_put (GTK_FIXED (fixed1), comboboxDestination, 168, 152);
  gtk_widget_set_size_request (comboboxDestination, 150, 35);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("Allemagne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("Alg\303\251rie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("Belgique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("Canada"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("Croatie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("Danemark"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("\303\211tats-Unis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("Espagne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("France"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("Italie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("Libye"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("Luxembourg"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("Maroc"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("Pays Bas"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("Portugal"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("Su\303\250de"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestination), _("Tunisie"));

  label_7 = gtk_label_new (_("Mois"));
  gtk_widget_show (label_7);
  gtk_fixed_put (GTK_FIXED (fixed1), label_7, 336, 256);
  gtk_widget_set_size_request (label_7, 48, 32);

  labelMsg = gtk_label_new ("");
  gtk_widget_show (labelMsg);
  gtk_fixed_put (GTK_FIXED (fixed1), labelMsg, 136, 336);
  gtk_widget_set_size_request (labelMsg, 432, 64);

  buttonAppliquer = gtk_button_new ();
  gtk_widget_show (buttonAppliquer);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonAppliquer, 296, 424);
  gtk_widget_set_size_request (buttonAppliquer, 100, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (buttonAppliquer), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label_15 = gtk_label_new_with_mnemonic (_("Appliquer"));
  gtk_widget_show (label_15);
  gtk_box_pack_start (GTK_BOX (hbox6), label_15, FALSE, FALSE, 0);

  buttonRetour = gtk_button_new ();
  gtk_widget_show (buttonRetour);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonRetour, 16, 8);
  gtk_widget_set_size_request (buttonRetour, 100, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttonRetour), alignment2);
  gtk_widget_set_size_request (alignment2, 69, -1);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label_16 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label_16);
  gtk_box_pack_start (GTK_BOX (hbox2), label_16, FALSE, FALSE, 0);

  label_3 = gtk_label_new (_("D\303\251stination"));
  gtk_widget_show (label_3);
  gtk_fixed_put (GTK_FIXED (fixed1), label_3, 48, 152);
  gtk_widget_set_size_request (label_3, 112, 35);

  label_4 = gtk_label_new (_("D\303\251part"));
  gtk_widget_show (label_4);
  gtk_fixed_put (GTK_FIXED (fixed1), label_4, 72, 64);
  gtk_widget_set_size_request (label_4, 80, 32);

  label_14 = gtk_label_new (_("Classe"));
  gtk_widget_show (label_14);
  gtk_fixed_put (GTK_FIXED (fixed1), label_14, 400, 64);
  gtk_widget_set_size_request (label_14, 80, 32);

  label_13 = gtk_label_new (_("Prix"));
  gtk_widget_show (label_13);
  gtk_fixed_put (GTK_FIXED (fixed1), label_13, 408, 152);
  gtk_widget_set_size_request (label_13, 56, 32);

  label_8 = gtk_label_new (_("Annee"));
  gtk_widget_show (label_8);
  gtk_fixed_put (GTK_FIXED (fixed1), label_8, 440, 256);
  gtk_widget_set_size_request (label_8, 72, 32);

  comboboxDepart = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxDepart);
  gtk_fixed_put (GTK_FIXED (fixed1), comboboxDepart, 168, 64);
  gtk_widget_set_size_request (comboboxDepart, 150, 35);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("Allemagne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("Alg\303\251rie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("Belgique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("Canada"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("Croatie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("Danemark"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("\303\211tats-Unis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("Espagne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("France"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("Italie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("Libye"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("Luxembourg"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("Maroc"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("Pays Bas"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("Portugal"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("Su\303\250de"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepart), _("Tunisie"));

  label_5 = gtk_label_new (_("Date de D\303\251part"));
  gtk_widget_show (label_5);
  gtk_fixed_put (GTK_FIXED (fixed1), label_5, 56, 288);
  gtk_widget_set_size_request (label_5, 120, 32);

  label_2 = gtk_label_new (_("Menu Ajout Vol"));
  gtk_widget_show (label_2);
  gtk_fixed_put (GTK_FIXED (fixed1), label_2, 296, 8);
  gtk_widget_set_size_request (label_2, 120, 35);

  g_signal_connect ((gpointer) buttonAppliquer, "clicked",
                    G_CALLBACK (on_buttonAppliquer_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonRetour, "clicked",
                    G_CALLBACK (on_buttonRetour_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MenuAjout, MenuAjout, "MenuAjout");
  GLADE_HOOKUP_OBJECT (MenuAjout, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (MenuAjout, spinbuttonJourDepart, "spinbuttonJourDepart");
  GLADE_HOOKUP_OBJECT (MenuAjout, spinbuttonMois, "spinbuttonMois");
  GLADE_HOOKUP_OBJECT (MenuAjout, spinbuttonAnnee, "spinbuttonAnnee");
  GLADE_HOOKUP_OBJECT (MenuAjout, spinbuttonPrix, "spinbuttonPrix");
  GLADE_HOOKUP_OBJECT (MenuAjout, comboboxClass, "comboboxClass");
  GLADE_HOOKUP_OBJECT (MenuAjout, label_6, "label_6");
  GLADE_HOOKUP_OBJECT (MenuAjout, comboboxDestination, "comboboxDestination");
  GLADE_HOOKUP_OBJECT (MenuAjout, label_7, "label_7");
  GLADE_HOOKUP_OBJECT (MenuAjout, labelMsg, "labelMsg");
  GLADE_HOOKUP_OBJECT (MenuAjout, buttonAppliquer, "buttonAppliquer");
  GLADE_HOOKUP_OBJECT (MenuAjout, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (MenuAjout, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (MenuAjout, image6, "image6");
  GLADE_HOOKUP_OBJECT (MenuAjout, label_15, "label_15");
  GLADE_HOOKUP_OBJECT (MenuAjout, buttonRetour, "buttonRetour");
  GLADE_HOOKUP_OBJECT (MenuAjout, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (MenuAjout, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (MenuAjout, image2, "image2");
  GLADE_HOOKUP_OBJECT (MenuAjout, label_16, "label_16");
  GLADE_HOOKUP_OBJECT (MenuAjout, label_3, "label_3");
  GLADE_HOOKUP_OBJECT (MenuAjout, label_4, "label_4");
  GLADE_HOOKUP_OBJECT (MenuAjout, label_14, "label_14");
  GLADE_HOOKUP_OBJECT (MenuAjout, label_13, "label_13");
  GLADE_HOOKUP_OBJECT (MenuAjout, label_8, "label_8");
  GLADE_HOOKUP_OBJECT (MenuAjout, comboboxDepart, "comboboxDepart");
  GLADE_HOOKUP_OBJECT (MenuAjout, label_5, "label_5");
  GLADE_HOOKUP_OBJECT (MenuAjout, label_2, "label_2");

  return MenuAjout;
}

GtkWidget*
create_MenuAgents (void)
{
  GtkWidget *MenuAgents;
  GtkWidget *fixed2;
  GtkWidget *treeviewListeVols;
  GtkWidget *entrySelection;
  GtkWidget *labelNotification;
  GtkWidget *entryrech;
  GtkWidget *buttonRetourP;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image11;
  GtkWidget *label21;
  GtkWidget *label_17;
  GtkWidget *buttonRechercher;
  GtkWidget *image10;
  GtkWidget *button1;
  GtkWidget *image12;
  GtkWidget *labelSelection;
  GtkWidget *buttonSupprimerVols;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label_23;
  GtkWidget *buttonAjouter;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label_22;
  GtkWidget *buttonModifierVol;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label_21;
  GtkWidget *buttonAfficher;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label12;

  MenuAgents = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (MenuAgents, 700, 500);
  gtk_window_set_title (GTK_WINDOW (MenuAgents), _("MenuAgents"));
  gtk_window_set_position (GTK_WINDOW (MenuAgents), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (MenuAgents), TRUE);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (MenuAgents), fixed2);

  treeviewListeVols = gtk_tree_view_new ();
  gtk_widget_show (treeviewListeVols);
  gtk_fixed_put (GTK_FIXED (fixed2), treeviewListeVols, 32, 64);
  gtk_widget_set_size_request (treeviewListeVols, 656, 272);

  entrySelection = gtk_entry_new ();
  gtk_widget_show (entrySelection);
  gtk_fixed_put (GTK_FIXED (fixed2), entrySelection, 272, 344);
  gtk_widget_set_size_request (entrySelection, 162, 31);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrySelection), 8226);

  labelNotification = gtk_label_new ("");
  gtk_widget_show (labelNotification);
  gtk_fixed_put (GTK_FIXED (fixed2), labelNotification, 136, 440);
  gtk_widget_set_size_request (labelNotification, 440, 48);

  entryrech = gtk_entry_new ();
  gtk_widget_show (entryrech);
  gtk_fixed_put (GTK_FIXED (fixed2), entryrech, 256, 24);
  gtk_widget_set_size_request (entryrech, 124, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryrech), 8226);

  buttonRetourP = gtk_button_new ();
  gtk_widget_show (buttonRetourP);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonRetourP, 8, 8);
  gtk_widget_set_size_request (buttonRetourP, 100, 40);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (buttonRetourP), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image11 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox10), image11, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox10), label21, FALSE, FALSE, 0);

  label_17 = gtk_label_new (_("Listes des vols"));
  gtk_widget_show (label_17);
  gtk_fixed_put (GTK_FIXED (fixed2), label_17, 264, 0);
  gtk_widget_set_size_request (label_17, 128, 24);

  buttonRechercher = gtk_button_new ();
  gtk_widget_show (buttonRechercher);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonRechercher, 384, 24);
  gtk_widget_set_size_request (buttonRechercher, 32, 32);

  image10 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_container_add (GTK_CONTAINER (buttonRechercher), image10);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed2), button1, 648, 8);
  gtk_widget_set_size_request (button1, 40, 32);

  image12 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_container_add (GTK_CONTAINER (button1), image12);

  labelSelection = gtk_label_new (_("Choisir une vol(ID)"));
  gtk_widget_show (labelSelection);
  gtk_fixed_put (GTK_FIXED (fixed2), labelSelection, 144, 344);
  gtk_widget_set_size_request (labelSelection, 120, 32);

  buttonSupprimerVols = gtk_button_new ();
  gtk_widget_show (buttonSupprimerVols);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonSupprimerVols, 528, 384);
  gtk_widget_set_size_request (buttonSupprimerVols, 104, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttonSupprimerVols), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label_23 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label_23);
  gtk_box_pack_start (GTK_BOX (hbox3), label_23, FALSE, FALSE, 0);

  buttonAjouter = gtk_button_new ();
  gtk_widget_show (buttonAjouter);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonAjouter, 64, 384);
  gtk_widget_set_size_request (buttonAjouter, 104, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (buttonAjouter), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label_22 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label_22);
  gtk_box_pack_start (GTK_BOX (hbox5), label_22, FALSE, FALSE, 0);

  buttonModifierVol = gtk_button_new ();
  gtk_widget_show (buttonModifierVol);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonModifierVol, 224, 384);
  gtk_widget_set_size_request (buttonModifierVol, 104, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (buttonModifierVol), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label_21 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label_21);
  gtk_box_pack_start (GTK_BOX (hbox4), label_21, FALSE, FALSE, 0);

  buttonAfficher = gtk_button_new ();
  gtk_widget_show (buttonAfficher);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonAfficher, 376, 384);
  gtk_widget_set_size_request (buttonAfficher, 104, 40);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (buttonAfficher), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox9), label12, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonRetourP, "clicked",
                    G_CALLBACK (on_buttonRetourP_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonRechercher, "clicked",
                    G_CALLBACK (on_buttonRechercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_refresh_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSupprimerVols, "clicked",
                    G_CALLBACK (on_buttonSupprimerVols_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAjouter, "clicked",
                    G_CALLBACK (on_buttonAjouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonModifierVol, "clicked",
                    G_CALLBACK (on_buttonModifierVol_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAfficher, "clicked",
                    G_CALLBACK (on_buttonAfficher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MenuAgents, MenuAgents, "MenuAgents");
  GLADE_HOOKUP_OBJECT (MenuAgents, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (MenuAgents, treeviewListeVols, "treeviewListeVols");
  GLADE_HOOKUP_OBJECT (MenuAgents, entrySelection, "entrySelection");
  GLADE_HOOKUP_OBJECT (MenuAgents, labelNotification, "labelNotification");
  GLADE_HOOKUP_OBJECT (MenuAgents, entryrech, "entryrech");
  GLADE_HOOKUP_OBJECT (MenuAgents, buttonRetourP, "buttonRetourP");
  GLADE_HOOKUP_OBJECT (MenuAgents, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (MenuAgents, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (MenuAgents, image11, "image11");
  GLADE_HOOKUP_OBJECT (MenuAgents, label21, "label21");
  GLADE_HOOKUP_OBJECT (MenuAgents, label_17, "label_17");
  GLADE_HOOKUP_OBJECT (MenuAgents, buttonRechercher, "buttonRechercher");
  GLADE_HOOKUP_OBJECT (MenuAgents, image10, "image10");
  GLADE_HOOKUP_OBJECT (MenuAgents, button1, "button1");
  GLADE_HOOKUP_OBJECT (MenuAgents, image12, "image12");
  GLADE_HOOKUP_OBJECT (MenuAgents, labelSelection, "labelSelection");
  GLADE_HOOKUP_OBJECT (MenuAgents, buttonSupprimerVols, "buttonSupprimerVols");
  GLADE_HOOKUP_OBJECT (MenuAgents, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (MenuAgents, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (MenuAgents, image3, "image3");
  GLADE_HOOKUP_OBJECT (MenuAgents, label_23, "label_23");
  GLADE_HOOKUP_OBJECT (MenuAgents, buttonAjouter, "buttonAjouter");
  GLADE_HOOKUP_OBJECT (MenuAgents, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (MenuAgents, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (MenuAgents, image5, "image5");
  GLADE_HOOKUP_OBJECT (MenuAgents, label_22, "label_22");
  GLADE_HOOKUP_OBJECT (MenuAgents, buttonModifierVol, "buttonModifierVol");
  GLADE_HOOKUP_OBJECT (MenuAgents, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (MenuAgents, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (MenuAgents, image4, "image4");
  GLADE_HOOKUP_OBJECT (MenuAgents, label_21, "label_21");
  GLADE_HOOKUP_OBJECT (MenuAgents, buttonAfficher, "buttonAfficher");
  GLADE_HOOKUP_OBJECT (MenuAgents, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (MenuAgents, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (MenuAgents, image9, "image9");
  GLADE_HOOKUP_OBJECT (MenuAgents, label12, "label12");

  return MenuAgents;
}

GtkWidget*
create_MenuModifier (void)
{
  GtkWidget *MenuModifier;
  GtkWidget *fixed3;
  GtkObject *spinbuttonJoursM_adj;
  GtkWidget *spinbuttonJoursM;
  GtkObject *spinbuttonMoisM_adj;
  GtkWidget *spinbuttonMoisM;
  GtkObject *spinbuttonAnneeM_adj;
  GtkWidget *spinbuttonAnneeM;
  GtkWidget *labelIdAModifier;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *label22;
  GtkWidget *comboboxDestinationM;
  GtkWidget *comboboxDepartM;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *comboboxClassM;
  GtkWidget *labelPrixM;
  GtkWidget *label25;
  GtkWidget *labelVolsModifier;
  GtkWidget *labelAnneeM;
  GtkWidget *labelMoisM;
  GtkWidget *labelJourM;
  GtkWidget *buttonRetourN;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label10;
  GtkWidget *labelMsgM;
  GtkWidget *buttonModifierN;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label11;

  MenuModifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (MenuModifier, 700, 500);
  gtk_window_set_title (GTK_WINDOW (MenuModifier), _("MenuModifier"));
  gtk_window_set_position (GTK_WINDOW (MenuModifier), GTK_WIN_POS_CENTER);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (MenuModifier), fixed3);
  gtk_widget_set_size_request (fixed3, 756, 628);

  spinbuttonJoursM_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonJoursM = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonJoursM_adj), 1, 0);
  gtk_widget_show (spinbuttonJoursM);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbuttonJoursM, 240, 296);
  gtk_widget_set_size_request (spinbuttonJoursM, 48, 25);

  spinbuttonMoisM_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonMoisM = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonMoisM_adj), 1, 0);
  gtk_widget_show (spinbuttonMoisM);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbuttonMoisM, 336, 296);
  gtk_widget_set_size_request (spinbuttonMoisM, 48, 24);

  spinbuttonAnneeM_adj = gtk_adjustment_new (2020, 2020, 2025, 1, 10, 10);
  spinbuttonAnneeM = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonAnneeM_adj), 1, 0);
  gtk_widget_show (spinbuttonAnneeM);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbuttonAnneeM, 416, 296);
  gtk_widget_set_size_request (spinbuttonAnneeM, 72, 24);

  labelIdAModifier = gtk_label_new ("");
  gtk_widget_show (labelIdAModifier);
  gtk_fixed_put (GTK_FIXED (fixed3), labelIdAModifier, 248, 8);
  gtk_widget_set_size_request (labelIdAModifier, 200, 35);

  spinbutton1_adj = gtk_adjustment_new (100, 100, 3000, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton1, 520, 160);
  gtk_widget_set_size_request (spinbutton1, 64, 24);

  label22 = gtk_label_new (_("D\303\251part"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed3), label22, 96, 88);
  gtk_widget_set_size_request (label22, 49, 17);

  comboboxDestinationM = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxDestinationM);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxDestinationM, 168, 80);
  gtk_widget_set_size_request (comboboxDestinationM, 180, 35);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("Allemagne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("Alg\303\251rie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("Belgique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("Canada"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("Croatie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("Danemark"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("\303\211tats-Unis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("Espagne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("France"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("Italie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("Libye"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("Luxembourg"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("Maroc"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("Pays Bas"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("Portugal"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("Su\303\250de"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDestinationM), _("Tunisie"));

  comboboxDepartM = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxDepartM);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxDepartM, 168, 160);
  gtk_widget_set_size_request (comboboxDepartM, 180, 35);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("Allemagne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("Alg\303\251rie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("Belgique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("Canada"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("Croatie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("Danemark"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("\303\211tats-Unis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("Espagne"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("France"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("Italie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("Libye"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("Luxembourg"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("Maroc"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("Pays Bas"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("Portugal"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("Su\303\250de"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxDepartM), _("Tunisie"));

  label23 = gtk_label_new (_("D\303\251stination"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed3), label23, 64, 168);
  gtk_widget_set_size_request (label23, 97, 24);

  label24 = gtk_label_new (_("Class"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed3), label24, 424, 88);
  gtk_widget_set_size_request (label24, 49, 17);

  comboboxClassM = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxClassM);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxClassM, 480, 80);
  gtk_widget_set_size_request (comboboxClassM, 180, 35);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxClassM), _("ClasseEconomique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxClassM), _("ClassePremium"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxClassM), _("CasseAffaire"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxClassM), _("ClassePremi\303\250re"));

  labelPrixM = gtk_label_new (_("Prix"));
  gtk_widget_show (labelPrixM);
  gtk_fixed_put (GTK_FIXED (fixed3), labelPrixM, 424, 160);
  gtk_widget_set_size_request (labelPrixM, 64, 27);

  label25 = gtk_label_new (_("Date de d\303\251part"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed3), label25, 80, 296);
  gtk_widget_set_size_request (label25, 112, 24);

  labelVolsModifier = gtk_label_new (_("Menu Modification Vol"));
  gtk_widget_show (labelVolsModifier);
  gtk_fixed_put (GTK_FIXED (fixed3), labelVolsModifier, 264, 16);
  gtk_widget_set_size_request (labelVolsModifier, 200, 35);

  labelAnneeM = gtk_label_new (_("Ann\303\251e"));
  gtk_widget_show (labelAnneeM);
  gtk_fixed_put (GTK_FIXED (fixed3), labelAnneeM, 424, 272);
  gtk_widget_set_size_request (labelAnneeM, 45, 20);

  labelMoisM = gtk_label_new (_("Mois"));
  gtk_widget_show (labelMoisM);
  gtk_fixed_put (GTK_FIXED (fixed3), labelMoisM, 328, 272);
  gtk_widget_set_size_request (labelMoisM, 56, 24);

  labelJourM = gtk_label_new (_("Jours"));
  gtk_widget_show (labelJourM);
  gtk_fixed_put (GTK_FIXED (fixed3), labelJourM, 232, 272);
  gtk_widget_set_size_request (labelJourM, 56, 24);

  buttonRetourN = gtk_button_new ();
  gtk_widget_show (buttonRetourN);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonRetourN, 16, 8);
  gtk_widget_set_size_request (buttonRetourN, 96, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (buttonRetourN), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox7), label10, FALSE, FALSE, 0);

  labelMsgM = gtk_label_new ("");
  gtk_widget_show (labelMsgM);
  gtk_fixed_put (GTK_FIXED (fixed3), labelMsgM, 144, 352);
  gtk_widget_set_size_request (labelMsgM, 424, 64);

  buttonModifierN = gtk_button_new ();
  gtk_widget_show (buttonModifierN);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonModifierN, 320, 432);
  gtk_widget_set_size_request (buttonModifierN, 96, 40);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (buttonModifierN), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Appliquer"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox8), label11, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonRetourN, "clicked",
                    G_CALLBACK (on_buttonRetourN_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonModifierN, "clicked",
                    G_CALLBACK (on_buttonModifierN_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MenuModifier, MenuModifier, "MenuModifier");
  GLADE_HOOKUP_OBJECT (MenuModifier, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (MenuModifier, spinbuttonJoursM, "spinbuttonJoursM");
  GLADE_HOOKUP_OBJECT (MenuModifier, spinbuttonMoisM, "spinbuttonMoisM");
  GLADE_HOOKUP_OBJECT (MenuModifier, spinbuttonAnneeM, "spinbuttonAnneeM");
  GLADE_HOOKUP_OBJECT (MenuModifier, labelIdAModifier, "labelIdAModifier");
  GLADE_HOOKUP_OBJECT (MenuModifier, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (MenuModifier, label22, "label22");
  GLADE_HOOKUP_OBJECT (MenuModifier, comboboxDestinationM, "comboboxDestinationM");
  GLADE_HOOKUP_OBJECT (MenuModifier, comboboxDepartM, "comboboxDepartM");
  GLADE_HOOKUP_OBJECT (MenuModifier, label23, "label23");
  GLADE_HOOKUP_OBJECT (MenuModifier, label24, "label24");
  GLADE_HOOKUP_OBJECT (MenuModifier, comboboxClassM, "comboboxClassM");
  GLADE_HOOKUP_OBJECT (MenuModifier, labelPrixM, "labelPrixM");
  GLADE_HOOKUP_OBJECT (MenuModifier, label25, "label25");
  GLADE_HOOKUP_OBJECT (MenuModifier, labelVolsModifier, "labelVolsModifier");
  GLADE_HOOKUP_OBJECT (MenuModifier, labelAnneeM, "labelAnneeM");
  GLADE_HOOKUP_OBJECT (MenuModifier, labelMoisM, "labelMoisM");
  GLADE_HOOKUP_OBJECT (MenuModifier, labelJourM, "labelJourM");
  GLADE_HOOKUP_OBJECT (MenuModifier, buttonRetourN, "buttonRetourN");
  GLADE_HOOKUP_OBJECT (MenuModifier, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (MenuModifier, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (MenuModifier, image7, "image7");
  GLADE_HOOKUP_OBJECT (MenuModifier, label10, "label10");
  GLADE_HOOKUP_OBJECT (MenuModifier, labelMsgM, "labelMsgM");
  GLADE_HOOKUP_OBJECT (MenuModifier, buttonModifierN, "buttonModifierN");
  GLADE_HOOKUP_OBJECT (MenuModifier, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (MenuModifier, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (MenuModifier, image8, "image8");
  GLADE_HOOKUP_OBJECT (MenuModifier, label11, "label11");

  return MenuModifier;
}

GtkWidget*
create_MenuPrincipale (void)
{
  GtkWidget *MenuPrincipale;
  GtkWidget *fixed4;
  GtkWidget *buttonReservationVols;
  GtkWidget *label16;
  GtkWidget *buttonGestionVols;
  GtkWidget *label15;
  GtkWidget *label14;

  MenuPrincipale = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (MenuPrincipale, 700, 500);
  gtk_window_set_title (GTK_WINDOW (MenuPrincipale), _("MenuPrincipale"));
  gtk_window_set_position (GTK_WINDOW (MenuPrincipale), GTK_WIN_POS_CENTER);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (MenuPrincipale), fixed4);

  buttonReservationVols = gtk_button_new_with_mnemonic (_("Acceder"));
  gtk_widget_show (buttonReservationVols);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonReservationVols, 448, 200);
  gtk_widget_set_size_request (buttonReservationVols, 100, 40);

  label16 = gtk_label_new (_("Reservervation Vols"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed4), label16, 432, 152);
  gtk_widget_set_size_request (label16, 136, 40);

  buttonGestionVols = gtk_button_new_with_mnemonic (_("Acceder"));
  gtk_widget_show (buttonGestionVols);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonGestionVols, 152, 200);
  gtk_widget_set_size_request (buttonGestionVols, 100, 40);

  label15 = gtk_label_new (_("Pr\303\251station Vols"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed4), label15, 112, 152);
  gtk_widget_set_size_request (label15, 168, 40);

  label14 = gtk_label_new (_("Menu Agents"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed4), label14, 240, 8);
  gtk_widget_set_size_request (label14, 192, 48);

  g_signal_connect ((gpointer) buttonReservationVols, "clicked",
                    G_CALLBACK (on_buttonReservationVols_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonGestionVols, "clicked",
                    G_CALLBACK (on_buttonGestionVols_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MenuPrincipale, MenuPrincipale, "MenuPrincipale");
  GLADE_HOOKUP_OBJECT (MenuPrincipale, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (MenuPrincipale, buttonReservationVols, "buttonReservationVols");
  GLADE_HOOKUP_OBJECT (MenuPrincipale, label16, "label16");
  GLADE_HOOKUP_OBJECT (MenuPrincipale, buttonGestionVols, "buttonGestionVols");
  GLADE_HOOKUP_OBJECT (MenuPrincipale, label15, "label15");
  GLADE_HOOKUP_OBJECT (MenuPrincipale, label14, "label14");

  return MenuPrincipale;
}

GtkWidget*
create_MenuResrvation (void)
{
  GtkWidget *MenuResrvation;
  GtkWidget *fixed6;
  GtkWidget *buttonRetourMP;

  MenuResrvation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (MenuResrvation, 700, 500);
  gtk_window_set_title (GTK_WINDOW (MenuResrvation), _("MenuResrvation"));
  gtk_window_set_position (GTK_WINDOW (MenuResrvation), GTK_WIN_POS_CENTER);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (MenuResrvation), fixed6);

  buttonRetourMP = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (buttonRetourMP);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonRetourMP, 120, 424);
  gtk_widget_set_size_request (buttonRetourMP, 100, 40);

  g_signal_connect ((gpointer) buttonRetourMP, "clicked",
                    G_CALLBACK (on_buttonRetourMP_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MenuResrvation, MenuResrvation, "MenuResrvation");
  GLADE_HOOKUP_OBJECT (MenuResrvation, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (MenuResrvation, buttonRetourMP, "buttonRetourMP");

  return MenuResrvation;
}

